---
# Application load paths
load_paths:
  - lib

# List of patterns for files to include
include:
  - "**/*.{rb,rake,erb}"

# List of patterns for files to exclude
exclude:
  - "{bin,node_modules,script,tmp,vendor}/**/*"

# Dictionary of constant name overrides
overrides:
  foobar: FooBar

# Weights for coupling criteria
weights:
  # Structural coupling
  structural: 1

  # Logical coupling
  logical: 1

  # Contributor coupling
  contributor: 1
